In [12]:
import numpy

In [2]:
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
type(n)

numpy.ndarray

In [4]:
n.reshape(3, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [6]:
m = numpy.asarray([[1, 2], [1, 2]])
m

array([[1, 2],
       [1, 2]])

In [2]:
import cv2

In [3]:
image = cv2.imread("smallgray.png", 0)
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
image  = cv2.imread("smallgray.png", 1)
image

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [5]:
#  Create an image using a given NumPy array
cv2.imwrite("newsmallgray.png", image)

True

In [7]:
image = cv2.imread("smallgray.png", 0)
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [8]:
image[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [9]:
for i in image :
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [10]:
#  Iterate through values
for i in image.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [14]:
#  Stacking more NumPy arrays
#  We have to pass a tuple as a parameter

#  Stack horizontally
import numpy
image_stacked = numpy.hstack((image, image))
image_stacked

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
#  Stack vertically
import numpy
image_stacked = numpy.vstack((image, image))
image_stacked

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [16]:
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [17]:
#  Split a NumPy array horizontally
split_h = numpy.hsplit(image, 5)
split_h

[array([[187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182]], dtype=uint8)]

In [18]:
#  Split a NumPy array vertically
split_v = numpy.vsplit(image, 3)
split_v

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]